an_number: AN00156
project: '{{an_number}}'
title: '{{an_number}}: Using the I2C master library'
version: 1.0.3

documentation:
  substitutions_path: doc/substitutions.inc
  exclude_patterns_path: doc/exclude_patterns.inc
  root_doc: doc/rst/AN00156.rst
  cognidox_part_number: XM-007836-AN
  pdfs:
    doc/rst/AN00156.rst:
      pdf_title: '{{title}}'
      pdf_filename: '{{an_number}}_v{{version}}'
      pdf_short: yes
    README.rst:
      pdf_title: '{{title}} (README)'
      pdf_filename: '{{an_number}}_v{{version}}_readme'
      pdf_short: yes

software:
  cognidox_part_number: XM-010179-SM
